 DROP DATABASE IF EXISTS Plabin_db;
 CREATE DATABASE Plabin_db;
 USE Plabin_db;
 
 -- Tabela FLORESTA
CREATE TABLE FLORESTA (
    ID_FLORESTA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_FLORESTA VARCHAR(100) NOT NULL,
    AREA_TOTAL DECIMAL(10, 2), 
    LOCALIZACAO VARCHAR(255)
);

-- Tabela TALHAO 
CREATE TABLE TALHAO (
    ID_TALHAO INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_TALHAO VARCHAR(50) UNIQUE NOT NULL,
    ESPECIE_MADEIRA VARCHAR(50) NOT NULL, 
    DATA_PLANTIO DATE,
    DATA_PREVISAO_COLHEITA DATE,
    ID_FLORESTA INT NOT NULL,
    FOREIGN KEY (ID_FLORESTA) REFERENCES FLORESTA(ID_FLORESTA)
        ON DELETE RESTRICT 
        ON UPDATE CASCADE
);


-- Tabela COLHEITA 
CREATE TABLE COLHEITA (
    ID_COLHEITA INT PRIMARY KEY AUTO_INCREMENT,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE,
    VOLUME_MADEIRA DECIMAL(10, 2), 
    ID_TALHAO INT NOT NULL,

    FOREIGN KEY (ID_TALHAO) REFERENCES TALHAO(ID_TALHAO)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- Tabela CERTIFICADO 
CREATE TABLE CERTIFICADO (
    ID_CERTIFICADO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CERTIFICADO VARCHAR(100) NOT NULL,
    ORG_EMISSOR VARCHAR(100),
    DATA_EMISSAO DATE,
    VALIDADE DATE
);



-- Tabela de ligação 
CREATE TABLE FLORESTA_CERTIFICADO (
    ID_FLORESTA INT NOT NULL,
    ID_CERTIFICADO INT NOT NULL,
    PRIMARY KEY (ID_FLORESTA, ID_CERTIFICADO), 
    FOREIGN KEY (ID_FLORESTA) REFERENCES FLORESTA(ID_FLORESTA)
        ON DELETE CASCADE,
    FOREIGN KEY (ID_CERTIFICADO) REFERENCES CERTIFICADO(ID_CERTIFICADO)
        ON DELETE CASCADE
);



-- Tabela PLANTA_PRODUCAO
CREATE TABLE PLANTA_PRODUCAO (
    ID_PLANTA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PLANTA VARCHAR(100) NOT NULL,
    LOCALIZACAO VARCHAR(255)
);

-- Tabela CELULOSE 
CREATE TABLE CELULOSE (
    ID_CELULOSE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_CELULOSE VARCHAR(50) NOT NULL, 
    DESCRICAO TEXT,
    UNIDADE_MEDIDA VARCHAR(10), 
    ID_PLANTA INT, 
    FOREIGN KEY (ID_PLANTA) REFERENCES PLANTA_PRODUCAO(ID_PLANTA)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- Tabela PAPEL 
CREATE TABLE PAPEL (
    ID_PAPEL INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_PAPEL VARCHAR(50) NOT NULL, 
    ESPECIFICACAO VARCHAR(100),
    PESO DECIMAL(8, 2), 
    ACABAMENTO VARCHAR(50),
    ID_CELULOSE_USADA INT NOT NULL, 
    ID_PLANTA INT,
    FOREIGN KEY (ID_CELULOSE_USADA) REFERENCES CELULOSE(ID_CELULOSE)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    FOREIGN KEY (ID_PLANTA) REFERENCES PLANTA_PRODUCAO(ID_PLANTA)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- Tabela EMBALAGEM 
CREATE TABLE EMBALAGEM (
    ID_EMBALAGEM INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_EMBALAGEM VARCHAR(50) NOT NULL, 
    DIMENSOES VARCHAR(100),
    USO_FINAL VARCHAR(100),
    ID_PAPEL_ORIGEM INT NOT NULL, 
    ID_PLANTA INT,
    FOREIGN KEY (ID_PAPEL_ORIGEM) REFERENCES PAPEL(ID_PAPEL)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    FOREIGN KEY (ID_PLANTA) REFERENCES PLANTA_PRODUCAO(ID_PLANTA)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);


-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CLIENTE VARCHAR(255) NOT NULL,
    CNPJ_CPF VARCHAR(20) UNIQUE,
    ENDERECO VARCHAR(255),
    CONTATO VARCHAR(100)
);

-- Tabela TRANSPORTE
CREATE TABLE TRANSPORTE (
    ID_TRANSPORTE INT PRIMARY KEY AUTO_INCREMENT,
    COD_RASTREAMENTO VARCHAR(50) UNIQUE NOT NULL,
    TRANSPORTADORA VARCHAR(100),
    DATA_ENVIO DATE,
    DATA_ENTREGA DATE
);

-- Tabela PEDIDO 
CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PEDIDO DATE NOT NULL,
    DATA_ENTREGA_PREV DATE,
    STATUS VARCHAR(50) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_TRANSPORTE INT UNIQUE, 
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    FOREIGN KEY (ID_TRANSPORTE) REFERENCES TRANSPORTE(ID_TRANSPORTE)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- Tabela ITEM_PEDIDO

CREATE TABLE ITEM_PEDIDO (
    ID_ITEM_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    QUANTIDADE DECIMAL(10, 2) NOT NULL,
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,    
    ID_CELULOSE INT NULL,
    ID_PAPEL INT NULL,
    ID_EMBALAGEM INT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
        ON DELETE CASCADE 
        ON UPDATE CASCADE,        
    FOREIGN KEY (ID_CELULOSE) REFERENCES CELULOSE(ID_CELULOSE)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,        
    FOREIGN KEY (ID_PAPEL) REFERENCES PAPEL(ID_PAPEL)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,        
    FOREIGN KEY (ID_EMBALAGEM) REFERENCES EMBALAGEM(ID_EMBALAGEM)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
        
);

-- Tabela ABASTECIMENTO_MADEIRA
CREATE TABLE ABASTECIMENTO_MADEIRA (
    ID_COLHEITA INT NOT NULL,
    ID_PLANTA INT NOT NULL,
    VOLUME_ENVIADO DECIMAL(10, 2) NOT NULL, 
    DATA_ENVIO DATE NOT NULL,   
    PRIMARY KEY (ID_COLHEITA, ID_PLANTA, DATA_ENVIO),     
    FOREIGN KEY (ID_COLHEITA) REFERENCES COLHEITA(ID_COLHEITA)
        ON DELETE RESTRICT 
        ON UPDATE CASCADE,        
    FOREIGN KEY (ID_PLANTA) REFERENCES PLANTA_PRODUCAO(ID_PLANTA)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);




